### ISSUE TITLE
Add attacking

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#102]
Let's add the ability to attack. I'd like it to be the left mouse button so we'll do that, let's change the right mouse button to be activate.
It'll then behave identically to activating, except it will call `on_hit` on scripts instead of `on_activate`. We'll need to add `on_hit` to the `Script` base class, which will have the same signature as `on_activate`.

**Comment by Soheil-Rasouli** [comment]
Hi @robbrit , May I work on this? I think I should work on ingame\controller file and scripts file and something in world.py.

**Comment by robbrit** [comment]
Hey @Soheil-Rasouli , send me a message on the [OSSU Discord](https://discord.gg/wuytwK5s9h) and let's have a chat. No problems with you working on it, but I prefer when everyone in the same place for any sort of announcements.
