### ISSUE TITLE
In-game Menu

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#13]
When in-game if the player hits Escape it should show an in-game menu.

Some notes:
* This will pause the game - the model should not update in this state.
* The menu should be a GUI that uses a GUI spec, same as the main screen.
* Currently this menu will only have one option which is Exit, but we'll add more later. When this item is activated, quit the game.

The way I'd do this is:
* Update `engine.ingame.controller.InGameController` to have a `setup()` method that accepts a `GameAPI` object, just like `engine.ingame.game_state.InGameState`.
* In `InGameState.setup()` it should call the controller's `setup()` method, passing in the `api` object.
* Update `engine.core.Core`'s, `engine.ingame.game_state.InGameState`'s, and `engine.ingame.game_state.InGameController`'s constructors to accept a `game_state.GUI` object called `menu_gui`. It will be wired through and saved in the `InGameController` object, it doesn't need to be saved anywhere else.
* In `InGameController` when escape is pressed, it should call the `set_gui()` method of the API object that it has, passing in the `menu_gui`.
* Create a `game.gui.ingame_menu.InGameMenu` class, modeled off of `game.gui.start.StartGame` but using a different spec for the menu.
* Create a function `game.gui.ingame_menu.exit` that exits the game. Technically we should handle exiting gracefully by having an `exit_game` method on `GameAPI` but we can do that in a later change. For now we can just do `sys.exit(0)`.
* The JSON spec for `StartGame` will specify that `exit()` function as its action.
* In the game's main method, pass an object of `InGameMenu` into `Core`'s constructor to tie that in.

**Comment by Exkywor** [comment]
Gonna start working on this, sorry for the delay
