### ISSUE TITLE
Render maps in the center

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#25]
If the active tile map is smaller than the viewport, it currently renders in the bottom left. We should render it in the center.

This can probably be done by clamping the camera coordinates.

**Comment by licjon** [comment]
I'm only familiar with clamping the camera when you want it to follow the character without showing the edge of the background image. 

My initial approach would be `if image width and height do not equal window width and height,` `arcade.set_viewport(left: image-width, right: window-width - image-width, bottom: image-height, top: window-height - image-height)`. 

My initial approach doesn't seem to be correct. I think that, ideally, I would like to set a location of origin for the camera from 0,0 to another coordinate.

**Comment by robbrit** [comment]
Right now the way it works is it tries to put the camera in a position where the player is in the exact center of the screen, but clamping when it gets to the edges of the map. This is to prevent us from showing nothingness beyond the edges.

The exception to this though would be if the size of the map is smaller than the viewport. In that case we do _not_ want to clamp, and instead just put the camera in a position such that the map is centered in the view. Probably something like `x = (map_width - viewport_width) / 2` (which would be a negative number).

You'd do the X and Y axes independently, it's possible that one dimension of the map is too small for the viewport, but the other is fine and so should follow the normal behaviour.
