### ISSUE TITLE
Game time

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#31]
We want to have the concept of "game time" so that scripts can do stuff based on some time value.

For now it should be simple enough just to track the number of seconds that the game has spent when it isn't paused.

The simplest way to do this is just to have a counter in the model that increments every time the `on_update` method is called.

**Comment by Jerry8538** [comment]
Is a simple counter as an attribute of Model okay? `on_update` is called 60 times per second, and a `game_time` method would return the time in seconds.

**Comment by robbrit** [comment]
> Is a simple counter as an attribute of Model okay?

Yup that's a good idea.

> on_update is called 60 times per second

It is _attempting_ to call it 60 times per second, it doesn't always guarantee that to be the case. The `dt` or `delta_time` parameter tells you the number of milliseconds that have passed since the previous update call, ensure to use that as the source of truth rather than a constant value.

> and a game_time method would return the time in seconds.

Yup sounds good, although to be "Pythonic" I'd use a [`@property`](https://docs.python.org/3/library/functions.html#property).

**Comment by Jerry8538** [comment]
> ensure to use that as the source of truth rather than a constant value.
Got it. Should I delete the pull request and create another? I cannot for the life of me get it to sync up your changes with my branch lol

**Comment by Jerry8538** [comment]
Should this issue be closed?
