### ISSUE TITLE
Prevent player from moving through NPCs

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#66]
Right now we have an NPC just hanging out, and the player can just walk right through it. This is less than ideal.

Let's expand the OOB (out of bounds) check to handle checks for _all_ solid objects. To do this, let's create a new sprite list as part of the model called "Solid Objects".

Some details about this sprite list:
* It's _only_ used for collision detection, we don't render it.
* Use spatial hashing for it.
* It can have overlap between itself and the other sprite lists, like scripted objects.

To construct this list, when we load the tileset we should populate it with all objects from the NPCs and the scripted objects layer that have a custom property "Solid" set to true (if the value doesn't exist, default to false).

Then when we do our `on_update`, instead of just checking for OOB we'll also check if there is an object in the solid objects sprite list at the target X and Y coordinates for our player (you can use [`get_sprites_at_point`](https://api.arcade.academy/en/latest/api/sprite_list.html#arcade-get-sprites-at-point) for that). If there is, don't allow the player to move.

**Comment by Jerry8538** [comment]
I'll take this one, to continue my wrangling with hitboxes.
