### ISSUE TITLE
Add a `get_sprites` method to `GameAPI`

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#69]
One thing that will be useful for scripts is a `get_sprites` method that will allow them to query the game for sprites matching a certain filter.

For now the main thing we'll want to query for is the name, which will then fetch a sprite with that name. Later on I'm thinking it'll be useful to have the idea of "tags", which are simple strings that can be attached to sprites and allow scripts to query for groups of sprites instead of just a specific one.

**Comment by r0hitm** [comment]
I will take this one
