### ISSUE TITLE
Validate GUI spec

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#7]
When we load in a GUI spec we should validate a number of things:

1. Any assets specified by buttons/images should exist.
1. The names used in button links should correspond to a button.
1. The center coordinates of anything should be on the screen.
1. Any names (assets, buttons, etc.) should be unique.
1. The button specified by `initial_selected_button` should exist.
1. There should be at least one button.
    * A corollary of this is that there should be at least one asset, but we don't need to explicitly check for that because of rule 1.

How I'd manage this:
* Create a `ValidationError` class that inherits from `Exception` in the `engine.gui.widgets` module with no constructor (so that it inherits the default behaviour from `Exception`).
* Create a method `validate` on the `GUISpec` class which raises the `ValidationError` and an appropriate message when the spec violates any of the criteria above.
* Instead of having `GUISpec.create` return the constructed object directly, it will create the object, call validate, and then return the object.
  * Note that we don't need `validate` to return anything; raising an exception is sufficient. This is the "Pythonic" way.

**Comment by licjon** [comment]
> Any assets specified by buttons/images should exist.

In GUISpec, where does `images=[Image(**b) for b in spec.get("images", [])]` get the images? In start-screen.json, I see assets and buttons, but I don't see images. Also should the spec be validated before creating because if there aren't any buttons, for example, wouldn't there be a key error? If so, would something like jsonschema be helpful for some of the validation (https://python-jsonschema.readthedocs.io/en/stable/)?

**Comment by robbrit** [comment]
> In GUISpec, where does images=[Image(**b) for b in spec.get("images", [])] get the images? In start-screen.json, I see assets and buttons, but I don't see images.

They'll be in the JSON file eventually, the intention is to allow someone specifying a GUI to put both buttons and images into the system. Buttons can be interacted with, but images cannot. Think of things like logos, background images, etc. They're currently not used in the code anywhere, I just created https://github.com/robbrit/ossu-game-project-1/issues/17 to handle support for those.

> Also should the spec be validated before creating because if there aren't any buttons, for example, wouldn't there be a key error?

There wouldn't be a `KeyError` since nothing tries to access the buttons if they aren't there. When you use `get()` on a dictionary in Python, it returns `None` if the key doesn't exist.

You're right though that there should be validation error if a button is referred to but doesn't exist. I'll update the list in the description of this ticket to include a check there.

> If so, would something like jsonschema be helpful for some of the validation (https://python-jsonschema.readthedocs.io/en/stable/)?

JSONSchema is a great tool, it'd be useful for ensuring that the spec matches the structure and types that we want. I'm not sure if the default named tuple processing does that, I haven't tested. The downside though would be that it'd require duplicating the named tuples that are defined in Python, since JSON schema requires you to write out the schema in JSON form. I wonder if it's possible to use `typings.NamedTuple` to validate types and structures at runtime as well as static check time, that would be a more robust solution since we wouldn't have to keep the JSON schemas and the named tuples in sync.

What I'm not sure about is if JSONSchema is powerful enough to express the constraints listed above (and therefore introducing it is solving a different problem than what this ticket is trying to do). For example, a constraint is that any value specified as `buttons.selected_image_asset` should exist as a value for `assets.name`. It is possible it can do this, I haven't explored a lot of the more niche features that it has, but at that point I wonder if it's worth introducing a new language or just doing it in Python.

**Comment by licjon** [comment]
OK, that helps. I didn't know what assumptions we should have about the GUI Spec. I am assuming that a spec must have at least 1 asset and at least 1 a button or image.

I am having trouble modifying the start-screen.json in a way I can test the validation errors.
- Everything seems to work normally if I change the value of buttons.selected_image_asset so it doesn't match assets.name (but changing unselected_image_asset causes a key error)
- Key error when assets.name is changed
- No error but nonworking button when value is changed for initial_selected_button or button.name (also does `(b for b in buttons if b.name == selected_button_name)` in GUIspec's create method make the check of "The button specified by initial_selected_button should exist" unnecessary?)


What Validation Errors are working so far:
- [X] Any names (assets, buttons, etc.) should be unique.
- [X] The center coordinates of anything should be on the screen.

**Comment by robbrit** [comment]
> I am assuming that a spec must have at least 1 asset and at least 1 button or image.

Technically speaking no, but it'd be a bit useless without it. So we can have that as a condition.

**Comment by licjon** [comment]
It appears that according to the type annotation in the Button class that center should be a tuple (`center: Tuple[int, int]`), but it is a list. Is it OK if I change `center=spec["center"]` to `center=tuple(spec["center"])` in the create method? That way I can use set to validate unique buttons, etc.

**Comment by licjon** [comment]
It appears that according to the type annotation in the Button class that center should be a tuple (`center: Tuple[int, int]`), but it is a list. Is it OK if I change `center=spec["center"]` to `center=tuple(spec["center"])` in the create method? That way I can use set to validate unique buttons, etc.

**Comment by licjon** [comment]
It appears that according to the type annotation in the Button class that center should be a tuple (`center: Tuple[int, int]`), but it is a list. Is it OK if I change `center=spec["center"]` to `center=tuple(spec["center"])` in the create method? That way I can use set to validate unique buttons, etc.

**Comment by licjon** [comment]
It appears that according to the type annotation in the Button class that center should be a tuple (`center: Tuple[int, int]`), but it is a list. Is it OK if I change `center=spec["center"]` to `center=tuple(spec["center"])` in the create method? That way I can use set to validate unique buttons, etc.

**Comment by robbrit** [comment]
> Is it OK if I change center=spec["center"] to center=tuple(spec["center"]) in the create method?

Yup that's fine.
