### ISSUE TITLE
Reverse the order of conversation options

### ISSUE THREAD

**Issue by robbrit** [robbrit/ossu-game-project-1#75]
Right now the conversation options render bottom to top. This is a bit counter-intuitive, we'd expect the one that is first in the list to appear on the top. Let's reverse the rendering order to do top to bottom.

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue.

**Comment by robbrit** [comment]
Sure @tarunsamanta2k20 , go for it.

**Comment by robbrit** [comment]
@tarunsamanta2k20 we normally communicate on this project in the OSSU Discord. Are you in there? I can send you an invite to the private channel we use, just let me know your username.

**Comment by robbrit** [comment]
@tarunsamanta2k20 removing you from this so that someone else can work on it.
